#! /usr/bin/env python3
# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2018-S1-MU-25 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018-S1-MU-25"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["Enceladus"] = \
 [ 84556, 84564, 84570, 84576, 84584, 84590, 84596, 84600, 84791, 84795, 84799, 84803, 84807, 84811, 84813, 84817, 84819, 84843, 84845, 84849, 84851, 84855, 84857, 84861, 84863, 84867, 84869, 84873, 84875, 84879, 84881, 84885, 84887, 84891,]

on["Titan"] = \
 [ 84276, 84278, 84282, 84284, 84286, 84288, 84292, 84294, 84296, 84298, 84300, 84346, 84348, 84352, 84356, 84360,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["Enceladus"] = ""
pars1["Titan"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["Enceladus"] = ""
pars2["Titan"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["Enceladus"] = ""
pars3["Titan"] = ""

# Found 2 source(s) for 2018-S1-MU-25

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
